services:
  app:
    env_file:
      - .env
    build: .
    container_name: realworldlitestar-${ENV}-app
    command: uv run litestar run --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      LITESTAR_APP: ${LITESTAR_APP}
      DB_HOST: ${DB_HOST:-postgres}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_ECHO: ${DB_ECHO}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      DEBUG: ${DEBUG}
    depends_on:
      - postgres
    volumes:
      - ./Conduit:/app/Conduit

  test:
    env_file:
      - .env
    build: .
    container_name: realworldlitestar-${ENV}-test
    command: pytest tests/ -p no:cacheprovider
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST:-postgres}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_ECHO: ${DB_ECHO}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      DEBUG: ${DEBUG}
    depends_on:
      - postgres
    volumes:
      - ./Conduit:/app/Conduit
      - ./tests:/app/tests

  postgres:
    image: postgres:16
    container_name: realworldlitestar-${ENV}-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_HOSTPORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: