services:
  postgres:
    image: postgres:16
    container_name: realworldlitestar-${ENV}-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_HOSTPORT}:${DB_CONTAINER_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: